services:
  - type: web
    name: gender-equality-advocacy
    env: node
    plan: free
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm start'
    envVars:
      - key: NODE_VERSION
        value: 20